[package]
name = "rabbitmq-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = "1.5.4"
tokio = "1.37.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
async-trait = "0.1.79"
