[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rs-snowflake = "0.6.0"
ulid = "1.1.3"
uuid = { version = "1.10.0", features = ["v4"] }
